### ISSUE TITLE
Confirm function

### ISSUE THREAD

**Issue by lkvitsinadze** [giorgijorji/laravel-tbc-installment#1]
When you try to use confirm function separately it does not work because it tries to get the session id from the object.
It would be good if sessionId could be transmitted from outside as well.

**Comment by giorgijorji** [comment]
Yes you are right, confirm method will get $sessionId from outside, I'll update it tomorrow to support $sessionId, confirm and cancel methods will be used after application applied and magazine got mail about installment... Will be updated tommorow, thanks for creating issue 👍

**Comment by giorgijorji** [comment]
Will update documentation too, it's now outdated and incorrect

**Comment by giorgijorji** [comment]
Fixed

**Comment by lkvitsinadze** [comment]
Great 👍
