### ISSUE TITLE
Error on confirm/cancel function

### ISSUE THREAD

**Issue by lkvitsinadze** [giorgijorji/laravel-tbc-installment#2]
When confirm/cancel request is not successful it causes fatal error.

`Call to undefined function Giorgijorji\LaravelTbcInstallment\report()`

I think it would be great if it will return status codes and also error messages got from TBC.

**Comment by giorgijorji** [comment]
Thanks for report will fix tomorrow. Yes I agree I'm planning to implement soon to remove this report method from catch block and return status codes with specific error messages. I will implement status codes and messages on this weekend.

**Comment by giorgijorji** [comment]
And also will add product price sum and total price amount validator before request sent to tbc api endpoint

**Comment by giorgijorji** [comment]
now it must be fixed, made many other improvements and products prices, structures, params and total prices are now validated, check for version 2.0.0

**Comment by giorgijorji** [comment]
Please fill free to test, I hadn't time to test cancel and confirm methods, as you will test and if you will  find any bugs I'll fix it instantly

**Comment by lkvitsinadze** [comment]
Thanks @giorgijorji,

I will test both methods and write you if there will be any problem.

**Comment by giorgijorji** [comment]
@lkvitsinadze thanks ^^

**Comment by lkvitsinadze** [comment]
@giorgijorji everything works fine for now. Thanks for help ^^

**Comment by giorgijorji** [comment]
That's Great! ^^ if there is any suggestions or improvements that can be made I'll make. In this version if you haven't seen there are new futures, this are:

- updated README.md
- more error handling
- Added product structure and parameters validator
- Added total price validator
- Support for adding multiple products at once
- Custom exceptions
- Now applyInstallmentApplication, confirm and cancel methods will return status code and message, based on status code you can do your stuff, status code 200 means all ok, any other code is error
